export { default as Properties } from "./dashboard/properties/Properties";
export { default as PropertyDetails } from "./dashboard/properties/PropertyDetials";
export {default as ManageProperty} from "./dashboard/properties/ManageProperty";
export { default as Home } from "./public/Home";
export { default as PageNotFound } from "./public/PageNotFound";
export { default as Login } from "./auth/Login";
export { default as Signup } from "./auth/Signup";
export { default as ResetPassword } from "./auth/ResetPassword";
export { default as Notification } from "./dashboard/Notification";
export { default as Settings } from "./dashboard/Settings";
export { default as Support } from "./dashboard/Support";
export { default as Report } from "./dashboard/Report";
export { default as Maintenance } from "./dashboard/maintenance/Maintenance";
